# Generated by Django 6.0.3 on 2026-03-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_category_goods_user_goods_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片'),
        ),
    ]
